[package]
name = "dogpost"
version = "0.1.0"
authors = ["Richard Dallaway <richard@dallaway.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
clap = "2.33"
imap = "1.0.2"
native-tls = "0.2" 
mailparse = "0.13"
mime-db = "1.1.0"
regex = "1.4"
chrono = "0.4"
rust-s3 = "0.26"
slug = "0.1"
thiserror = "1.0"
